name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: |
          echo ${{ matrix.node-version }}
          echo "Hello, world!" ${{ matrix.node-version }} > output_${{ matrix.node-version }}.txt

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v2
        with:
          name: output_${{ matrix.node-version }}.txt
          path: './'  # Customize this path based on your build output location

  release:
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        node-version: [14.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: output_${{ matrix.node-version }}.txt

      - name: Unzip and display artifacts
        run: |
          cat output_${{ matrix.node-version }}.txt
